# Generated by Django 2.1.4 on 2018-12-04 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SportBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('w1', models.FloatField(default=2.64)),
                ('w2', models.FloatField(default=2.64)),
                ('d', models.FloatField(default=2.64)),
                ('status', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.FloatField(default=1)),
                ('status', models.IntegerField(default=0)),
                ('bet', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainGameApp.SportBet')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
