# Generated by Django 2.1.4 on 2018-12-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainGameApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportbet',
            name='status',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
