# Generated by Django 2.1.4 on 2018-12-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainGameApp', '0003_userbet_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbet',
            name='betValue',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
